spring:
  application:
    name: portfolio-aggregator-backend
  profiles:
    active: testdata
oauth:
  access-token:
    refresh:
      lookahead-in-seconds: 5
      uri:
        questrade: https://login.questrade.com/oauth2/token